### ISSUE TITLE
员工管理界面下拉列表内容错误

### ISSUE THREAD

**Issue by AxisWhistle** [NJU-DMS-Team/dms#12]
+ **监理** vs **管理**
     实际显示中有个中心为“监理”
     代码中为GUAN_LI（管理）
     所以应该为哪个？

+ 校区显示下拉列表为空

**Comment by xwang1024** [comment]
下拉列表已经ok

**Comment by Jason121250148** [comment]
确认是**监理**
后台代码枚举是GUAN_LI
不要修改
成为缺陷
