### ISSUE TITLE
分页显示+多选的时候有问题，详情见comment

### ISSUE THREAD

**Issue by Jason121250148** [NJU-DMS-Team/dms#21]
比如员工管理，在某一页勾选一个，然后翻页，再勾选一个，修改按钮可以点击，此时前一页的员工是勾选状态，这时候不是勾选了两个人么，不知道算不算bug

**Comment by xwang1024** [comment]
算

**Comment by AxisWhistle** [comment]
标题可以不用写详情见comment
@Jason121250148

**Comment by xwang1024** [comment]
fixed
@Jason121250148
