### ISSUE TITLE
迁入员工问题：夫妻房无法分配

### ISSUE THREAD

**Issue by Jason121250148** [NJU-DMS-Team/dms#35]
试图分配一个夫妻房给jack9,（他提交了夫妻房的申请，申请未处理），但是搜索不到jack9，只能添加rose8，但是rose8是单身
记得分房是要有申请才能够分，就算是换宿舍也得要有申请

**Comment by xwang1024** [comment]
哲理有一个问题，不知道后端那边有没有限制，前端是有问题，分房的时候看的不是申请的类型而是实际的性别。。。

**Comment by Jason121250148** [comment]
分房的时候应该是从所有NEW和OFFICE_APPROVED这两种状态的宿舍申请中筛选，已经分了的和被拒绝的都要重新提交申请。后台没有关于性别的限制，如果把男的分到女的宿舍只能算操作人员的失误了=。=
