### ISSUE TITLE
中心创建员工时是否可以选择其它中心

### ISSUE THREAD

**Issue by AxisWhistle** [NJU-DMS-Team/dms#48]
比如校园中心账号登录，创建员工时是只能创建校园中心的员工？还是可以创建其它中心的员工？

关联配偶时可以选择其它中心的员工吗？

**Comment by xwang1024** [comment]
创建已经做限制，目前中心关联配偶只能关联自己中心的，只有办公室可以关联其它中心的
@AxisWhistle
