### ISSUE TITLE
办公室分配宿舍的时候 点击迁入后的界面 选择员工时 如果员工太多的话寻找比较困难

### ISSUE THREAD

**Issue by whqwhq1994** [NJU-DMS-Team/dms#57]
![image](https://cloud.githubusercontent.com/assets/12732065/9567056/9fdef83a-4f4f-11e5-91aa-f3aa6ccfbe5d.png)

**Comment by AxisWhistle** [comment]
这个可以输入部分信息自动筛选

**Comment by AxisWhistle** [comment]
不过存在问题
![image](https://cloud.githubusercontent.com/assets/7236630/9653312/331f4a48-5255-11e5-8a87-01da2f6c54d8.png)
@xwang1024
