### ISSUE TITLE
cannot read JSON 

### ISSUE THREAD

**Issue by AxisWhistle** [NJU-DMS-Team/dms#59]
![image](https://cloud.githubusercontent.com/assets/7236630/9567239/654335d6-4f56-11e5-844a-2a19eb15d4f9.png)

**Comment by AxisWhistle** [comment]
目测是数据格式不一致
@xwang1024

**Comment by xwang1024** [comment]
协议：
POST /api/DormitoryApplication/officeReject
{
    "id" : 1
}
实际：
Request URL:http://localhost:8080/dms/api/DormitoryApplication/officeReject
Request Method:POST
Request Payload:
{"id":10}

@AxisWhistle

**Comment by xwang1024** [comment]
基本确认为服务器大姨妈问题....重新install几次就好了..

@AxisWhistle
